#!/bin/sh

DHCPVARFILE=/tmp/udhcpc.$interface

echo "IPADDR=$ip" >> $DHCPVARFILE
echo "HOSTNAME=$hostname" >> $DHCPVARFILE
echo "NETMASK=$subnet" >> $DHCPVARFILE
echo "BROADCAST=$broadcast" >> $DHCPVARFILE
echo "DOMAINNAME=$domain" >> $DHCPVARFILE

echo $hostname > /etc/hostname
/bin/hostname $hostname