#!/bin/sh
#
# "Sali" 
#
#  Copyright (C) 2010 SARA Computing and Networking Services
#  Copyright (C) 1999-2005 Brian Elliott Finley
#
#  $Id: functions 4468 2009-04-10 00:40:13Z bli $
#  vi: set filetype=sh et ts=4:
#
#  Authors:
#   Bas van der Vlies
#   Dennis Stam
#
#  Original authors and contributers:
#   Brian
#   Elliot
#   Finley
#   Charles C. Bennett, Jr. <ccb@acm.org>
#   Sean Dague <japh@us.ibm.com>
#   Dann Frazier <dannf@dannf.org>
#   Curtis Zinzilieta <czinzilieta@valinux.com>
#


################################################################################
#
#   Variables
#
PATH=/sbin:/bin:/usr/bin:/usr/sbin:/tmp
LD_LIBRARY_PATH=/lib

SCRIPTS=scripts
SCRIPTS_DIR=/scripts

TORRENTS=torrents
TORRENTS_DIR=/torrents

VERSION="SYSTEMIMAGER_VERSION_STRING"
FLAVOR="SYSTEMIMAGER_FLAVOR_STRING"
#
################################################################################

################################################################################
#
## SALI Just start udev, don't use the static dev.tar.gz
start_udevd() {
    #
    # Start udevd first, then hotplug

    logmsg
    logmsg start_udevd
    /etc/init.d/udev start
}
