#!/bin/sh

VERSION="SYSTEMIMAGER_VERSION_STRING"
STUBDIR="/etc/sali/stubs"
FUNCTIONSFILE="/etc/init.d/functions"
TMPFILE="/etc/sali/functions.$$"

stub_file(){
	echo $(ls -1 $STUBDIR)
}

append_to_file(){
	src_file=$1
	dst_file=$2

	cat $src_file >> $dst_file
}

move_tmp_file(){
	src_file=$1
	dst_file=$2

	mv $src_file $dst_file
	chmod 755 $dst_file
}

while true
do
	case "$1" in
		-s|--stubsdir)
			if [ -e $2 ]; then
				STUBDIR=$2
			else
				echo "Specified stubsdir not found, stopping"
				exit 1
			fi
			shift 2
		;;
		-f|--functionsfile)
			FUNCTIONSFILE=$2
			if [ ! -e $FUNCTIONSFILE ]; then
				touch $FUNCTIONSFILE
			fi
			shift 2
		;;
		-t|--tmpfile)
			TMPFILE=$2
			if [ ! -e $TMPFILE ]; then
				touch $TMPFILE
			fi
			shift 2
		;;
		-m|--makefile)
			BYMAKEFILE=true
			shift
		;;
		*)
			break
		;;
	esac
done

## Showing some information about the directories
echo "sali_functions for Sali $VERSION"
echo "stubs directory     : $STUBDIR"
echo "functions file      : $FUNCTIONSFILE"
echo "tmp functions file  : $TMPFILE"

for file in $(stub_file $STUBDIR); do
	if [ ! $( echo $file | grep header ) ]; then
		echo -e "##BEGIN $file" >> $TMPFILE
	fi

	append_to_file $STUBDIR/$file $TMPFILE

	if [ ! $( echo $file | grep header ) ]; then
		echo -e "##END $file" >> $TMPFILE
	fi
done

CURDATE=$(date)
echo -e "\n\n\n" >> $TMPFILE
echo -e "################################################################################" >> $TMPFILE
echo -e "# This file has been created by sali_function for sali-$VERSION" >> $TMPFILE
echo -e "# DATE         : $CURDATE" >> $TMPFILE
echo -e "# STUBDIR      : $STUBDIR" >> $TMPFILE
echo -e "# FUNCTIONSFILE: $FUNCTIONSFILE" >> $TMPFILE
echo -e "################################################################################" >> $TMPFILE

if [ -z $BYMAKEFILE ]; then
	move_tmp_file $TMPFILE $FUNCTIONSFILE
fi
