#!/bin/bash
#
# A simple script to install the bootloader
#
#set -x

## Include the os-release file, so we can determine how to configure the bootloader
source /etc/os-release

GRUB_TARGET_PC=i386-pc
GRUB_TARGET_EFI="$(uname -m)-efi"

GRUB_LIB_DIR=""
GRUB_INSTALL=""

grub2_check_installed(){

    ## Things are different per distro
    case "${ID}" in
        debian)
            GRUB_LIB_DIR=/usr/lib/grub
            GRUB_INSTALL=/usr/sbin/grub-install
        ;;
        centos)
            GRUB_LIB_DIR=/usr/lib/grub
            GRUB_INSTALL=/usr/sbin/grub2-install
        ;;
        sles)
            GRUB_LIB_DIR=/usr/lib/grub2
            GRUB_INSTALL=/usr/sbin/grub2-install
        ;;
    esac

}

grub2_configure(){

    ## Things are different per distro
    case "${ID}" in
        debian)
            grub_cfg_command="/usr/sbin/update-grub"
        ;;
        centos|sles)
            grub_cfg_command="/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg"
        ;;
    esac

    $grub_cfg_command
}

### MAIN
grub2_check_installed

## Check if we have grub
if [ ! -x "${GRUB_INSTALL}" ]
then
    echo "Could not locate grub-install command at \"${GRUB_INSTALL}\""
    exit 1
fi

## Just to install legacy BIOS boot if we can
if [[ -d ${GRUB_LIB_DIR}/${GRUB_TARGET_PC} ]]
then
    $GRUB_INSTALL --no-floppy --target $GRUB_TARGET_PC $1
fi

## UEFI boorlader with fail back boot efi loader and do not update efi nvram
$GRUB_INSTALL --no-floppy --target $GRUB_TARGET_EFI --no-nvram  --force-extra-removable $1
if [[ $? -gt 0 ]]
then
    echo "UEFI boot install FAILED"
    exit 1
fi

## We also need to update the configuration
echo "Updating grub.cfg"
grub2_configure
