#!/bin/sh


## Mounting some important filesystems
mkdir -p /proc
mount proc /proc -t proc

mkdir -p /sys
mount sysfs /sys -t sysfs
## End

init="/sbin/init"
for i in $(cat /proc/cmdline); do
    case $i in
        init=*)
            init=${i#init=}
            ;;  
		BLACKLIST=*)
			blacklist=${i#BLACKLIST=}
		;;
    esac
done

if [ -n "${blacklist}" ]
then
	cat /dev/null > /etc/modprobe.d/pxe_blacklist.conf
	for module in $(echo $blacklist | tr ';' ' ')
	do
		echo "blacklist ${module}" >> /etc/modprobe.d/pxe_blacklist.conf
	done
fi

echo -e "Starting udev...\n"

make_extra_nodes() {
  [ -e /etc/udev/links.conf ] || return 0
  grep '^[^#]' /etc/udev/links.conf | \
  while read type name arg1; do
    [ "$type" -a "$name" -a ! -e "/dev/$name" -a ! -L "/dev/$name" ] ||continue
    case "$type" in
      L) ln -s $arg1 /dev/$name ;;
      D) mkdir -p /dev/$name ;;
      M) mknod -m 600 /dev/$name $arg1 ;;
      *) echo "links.conf: unparseable line ($type $name $arg1)" ;;
    esac
  done
}

## Starting udev

echo > /sys/kernel/uevent_helper

mount -n -o mode=0755 -t tmpfs tmpfs /dev
make_extra_nodes

udevd --daemon

mkdir -p /dev/.udev/db/ /dev/.udev/queue/
udevadm trigger

mkdir -p /dev/pts
mount devpts /dev/pts -t devpts

if [ -d /sys/bus/scsi ]; then
    modprobe -q scsi_wait_scan && modprobe -r scsi_wait_scan || true
    udevadm settle || true
fi

dmesg -n 6

touch /tmp/si_monitor.log

echo -e "Done with udev initialization, starting sali...\n"

exec $init
