#!/bin/sh
# Currently, we only dispatch according to command.  However, a more
# elaborate system might dispatch by command and interface or do some
# common initialization first, especially if more dhcp event notifications
# are added.

DHCPVARFILE=/tmp/udhcpc

echo "IMAGESERVER=$sisrv" > $DHCPVARFILE
echo "IPADRR=$ip" >> $DHCPVARFILE
echo "HOSTNAME=$hostname" >> $DHCPVARFILE
echo "NETMASK=$subnet" >> $DHCPVARFILE

exec /etc/udhcpc/default.$1
