#!/bin/sh

DHCPVARFILE=/tmp/udhcpc

echo "SALIIMAGESRV=$saliimgsrv" > $DHCPVARFILE
echo "IPADDR=$ip" >> $DHCPVARFILE
echo "HOSTNAME=$hostname" >> $DHCPVARFILE
echo "NETMASK=$subnet" >> $DHCPVARFILE
echo "BROADCAST=$broadcast" >> $DHCPVARFILE
echo "DOMAINNAME=$domain" >> $DHCPVARFILE
