#!/bin/sh

. /etc/init.d/functions

## Let's begin with some nice headers
echo
p_header
echo
p_separator
echo

## Now the startup section
p_section "Intializing SALI environment"

## Now loop trought the different files
for file in $(ls -1 $SALI_STARTUP_D_DIR)
do
    . $SALI_STARTUP_D_DIR/$file

    if [ $? -ne 0 ]
    then
        open_console error_startup
    fi

    save_variables
done 
