#!/bin/sh
#
# This file is part of SALI
#
# SALI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SALI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied:ta warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SALI.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010-2015 SURFsara

###
# $Id$
# $URL$
###

## First include the functions file
. /etc/init.d/functions

## Check wether we must open a console instead of installing a new image
if [ $(is_yes $SALI_RESCUE) -eq 1 ]
then
    p_stage "Opening console"
    open_console

    exit 0
fi

if [ -z "${SALI_IMAGESERVER}" ]
then
    p_stage "Missing value for SALI_IMAGESERVER"
    p_service "Please add a value for SALI_IMAGESERVER in the console"
    p_comment 0 "Type: SALI_IMAGESERVER=<ip|hostname>"
    p_comment 0 "Type: save_variables"
    p_comment 0 "Type: exit"
    open_console
fi
if [ -z "${SALI_IMAGENAME}" ]
then
    p_stage "Missing value for SALI_IMAGENAME"
    p_service "Please add a value for SALI_IMAGENAME in the console"
    p_comment 0 "Type: SALI_IMAGENAME=<name>"
    p_comment 0 "Type: save_variables"
    p_comment 0 "Type: exit"
    open_console
fi

if [ ! -e "$SALI_CACHE_DIR/installer_first_try" ]
then
    touch $SALI_CACHE_DIR/installer_first_try
else
    p_stage "This process is a respawn, opening console"
    open_console
    exit 1
fi

## Let's show what this script does
echo
p_section "Starting installation process"

## Now loop trough the different scripts
for file in $(ls -1 $SALI_INSTALLER_D_DIR)
do
    . $SALI_INSTALLER_D_DIR/$file
done

echo "Dev mode"
open_console
