#!/bin/sh
#
# This file is part of SALI
#
# SALI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SALI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SALI.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010-2021 SURF

. /etc/init.d/functions

## Let's begin with some nice headers
echo
p_header
echo
p_separator
echo

## Now the startup section
p_section "Intializing SALI environment"

## Now loop trought the different files
for file in $(ls -1 $SALI_STARTUP_D_DIR)
do
    . $SALI_STARTUP_D_DIR/$file

    ## When a stage script exits with greater then 0, open the console
    if [ $? -ne 0 ]
    then
        open_console error_startup
    fi

    save_variables
done 
