#!/bin/sh
#
# This file is part of SALI
#
# SALI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SALI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SALI.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2010-2015 SURFsara

###
# $Id$
# $URL$
###

## For init we don't want to rely on $PATH
_PRINTF="/usr/bin/printf"
_MOUNT="/bin/mount"
_MKDIR="/bin/mkdir"
_UDEVD="/lib/udev/udevd"
_UDEVADM="/usr/bin/udevadm"
_DMESG="/bin/dmesg"

## Default value for init
init="/sbin/init"

## Fast scan of the kernel paramaters
for option in $(cat /proc/cmdline)
do
    case "${option}" in
        init=*)
            init=${option#init=}
        ;;
        BLACKLIST=*)
            blacklist=${option#BLACKLIST=}
        ;;
    esac
done

## Creating blacklist file
if [ -n "${blacklist}" ]
then
    # Create modprobe dir when it does not exists
    if [ ! -d "/etc/modprobe.d" ]
    then
        $_MKDIR /etc/modprobe.d
    fi

    # Make sure the file exists and is empty
    $_CAT /dev/null > /etc/modprobe.d/pxe_blacklist.conf
    for module in $(echo $blacklist | sed 's/;/ /g')
    do
        $_PRINTF "blacklist ${module}\n" >> /etc/modprobe.d/pxe_blacklist.conf
    done
fi

## Some preparations
if [ ! -d "/dev" ]
then
    $_MKDIR /dev
fi
$_MOUNT -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

####
## Now the real initialization of SALI
$_PRINTF "Initializing SALI...\n"

## Starting udev
$_UDEVD -d || ($_PRINTF "Failed to start UDEV\n" && exit 1)
$_UDEVADM trigger --type=subsystems --action=add
$_UDEVADM trigger --type=devices --action=add
$_UDEVADM settle --timeout=30 || $_PRINTF "Udevadm settle failed\n"

$_PRINTF "Done with udev initalization, continue booting into SALI...\n"

# Change console-level to 6
$_DMESG -n 6

## Now start SALI
exec $init
