#!/usr/bin/env python
#
# "SALI"
#
# Copyright (c) 2010 SARA Computing and Networking Services
#
#   $Id$

import sys

try:
    from sali import general
    from sali import server
except ImportError:
    sys.path.append( '../' )

    from sali import general
    from sali import server

if __name__ == '__main__':

    if len( sys.argv ) == 3:
        CFGFILE = sys.argv[ 1 ]
        ACTION = sys.argv[ 2 ]
    else:
        print 'Could not execute command. Usage: %s /path/to/config start|stop|restart|fg|help' % sys.argv[ 0 ]
        sys.exit( 1 )

    cfg = general.Config( CFGFILE )

    if ACTION in [ 'start', 'stop', 'restart' ]:
        dc = general.DaemonCtl( server.sali_server, cfg )

        if ACTION == 'start':
            dc.start()
        elif ACTION == 'stop':
            dc.stop()
        elif ACTION == 'restart':
            dc.restart()
    elif ACTION == 'fg':
        dc = general.DaemonCtl( server.sali_server, cfg, foreground=True )
        dc.start()
    elif ACTION == 'help':
        print( 'Show some nice help' )
