#!/bin/sh
#
#   "SALI"
#
#   Copyright (C) 2010 SARA Computing and Networking Services
#
#   $Id$
#    vi: set filetype=make:
#
# ----
#
#   "SystemImager" 
#
#   Copyright (C) 1999-2004 Brian Elliott Finley 
#
#   Others who have contributed to this code:
#       Charles C. Bennett, Jr. <ccb@acm.org>
#       Sean Dague <japh@us.ibm.com>
#       Dann Frazier <dannf@dannf.org>
#       Curtis Zinzilieta <czinzilieta@valinux.com>
#

#set -x         # can be uncommented for debug purposes

#################################################################################
#   Load functions and other variables
#
. /etc/init.d/functions
#
################################################################################

#################################################################################
#
#   main
#
{

if [ ! -z $SSH_DOWNLOAD_URL ]; then
    SSH=y
fi
if [ "x$SSH" = "xy" ]; then
    logmsg
    logmsg start_ssh
    start_ssh
fi

logmsg "$PROTOCOL"
if [ "x$PROTOCOL" = "x" ]
then
	old_getimage
fi

run_pre_install_scripts

# if scriptname is not specified open the console!
if [ -z $SCRIPTNAME ]; then
    logmsg
    logmsg "No script defined, opening console"
    write_variables
    shellopen
fi

# If none of SCRIPTNAME, HOSTNAME, or IMAGENAME is set, then we cannot proceed.
# (IMAGENAME may have been set by local.cfg).  -BEF-
if [ -z $SCRIPTNAME ] && [ -z $IMAGENAME ] && [ -z $HOSTNAME ]; then
    logmsg
    logmsg "FATAL:  None of SCRIPTNAME, IMAGENAME, or HOSTNAME were set, and I"
    logmsg "can no proceed!  (Scottish accent -- think Groundskeeper Willie)"
    logmsg
    logmsg "HOSTNAME is what most people use, and I try to determine it automatically"
    logmsg "from this hosts IP address ($IPADDR) in the following order:"
    logmsg
    logmsg "  1)  /var/lib/systemimager/scripts/hosts on your imageserver"
    logmsg "  2)  DNS"
    logmsg
    logmsg "Finally, you can explicitly set many variables pre-boot, including SCRIPTNAME,"
    logmsg "IMAGENAME, and HOSTNAME, as kernel append parameters or with a local.cfg file."
    logmsg
    shellout
fi
write_variables
    
choose_autoinstall_script

write_variables

run_autoinstall_script

} 2>&1 | send_monitor_stdout

#
#################################################################################

exit 0

