#!/bin/sh
#
# Author: Dennis Stam
# Date  : 6 March 2013
# Desc. : Copy the the firmwares from SRC_DIR/linux-firmware to 
#         INITRD_BUILD_DIR/lib/firmware
#
# SVn Info:
# 	$Id$
#       $URL$
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
if [ $# -lt 1 ]
then
	echo "Usage: $(basename $0) <SRC_DIR> <INITRD_BUILD_DIR>"
	exit 0
fi

## Some definiction given by the user
SRC_DIR=$1
INITRD_BUILD_DIR=$2

FIRMWARE_SRC="${SRC_DIR}/linux-firmware"
KERNEL_MODULES_DIR="${INITRD_BUILD_DIR}/lib/modules"
KERNEL_FIRMWARE_DIR="${INITRD_BUILD_DIR}/lib/firmware"

MODINFO=$(which modinfo)

for module in $(find "${KERNEL_MODULES_DIR}" -name "*.ko" -type f)
do
    for firmware in $($MODINFO $module | awk '/^firmware/ {print $2}')
    do
        if [ ! -f "${KERNEL_FIRMWARE_DIR}/${firmware}" ]
        then
            LOCATION=$(dirname "${KERNEL_FIRMWARE_DIR}/${firmware}")
            if [ ! -d "${LOCATION}" ]
            then
                mkdir -p "${LOCATION}"
            fi
            if [ -f "${FIRMWARE_SRC}/${firmware}" ]
            then
                cp -a "${FIRMWARE_SRC}/${firmware}" "${KERNEL_FIRMWARE_DIR}/${firmware}"
            fi
        fi
    done
done
