#!/usr/bin/env python
#
# "SALI"
#
# Copyright (c) 2010 SARA Computing and Networking Services
#
#   $Id$

from __future__ import print_function

import sys

try:
    from sali import general
    from sali import server
except ImportError:
    sys.path.append( '../python-libs' )

    from sali import general
    from sali import server

if __name__ == '__main__':

    if len( sys.argv ) == 3:
        CFGFILE = sys.argv[ 1 ]
        ACTION = sys.argv[ 2 ]
    else:
        print( 'Could not execute command. Usage: %s /path/to/config start|stop|restart|fg|help' % sys.argv[ 0 ] )
        sys.exit( 1 )

    cfg = general.Config( CFGFILE )

    if ACTION in [ 'start', 'stop', 'restart' ]:
        daemon = server.sali_server( cfg )

        if ACTION == 'start':
            daemon.start()
        elif ACTION == 'stop':
            daemon.stop()
        elif ACTION == 'restart':
            daemon.restart()
    elif ACTION == 'fg':
        daemon = server.sali_server( cfg, fg=True )
        daemon.start()
    elif ACTION == 'help':
        print( 'Show some nice help' )
